-- ASSIGNMENT 6
/*1. Create a view named ‘customer_san_jose’ which comprises of only those
customers who are from San Jose*/



CREATE TABLE CUSTOMERS(
CUSTOMER_ID INT, FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
EMAIL VARCHAR(50),
ADDRESS VARCHAR(50),
CITY VARCHAR (50),
STATE VARCHAR(50),
ZIP INT
);
INSERT INTO CUSTOMERS 
VALUES
(10,'JEMMI','JORDAN','JEM@GMAIL.COM','2ND FLOOR GANDHI NAGAR','SANJOSE','KARNATAKA',67643),(20,'KUNAL','KUSH','KUNAL@GMAIL.COM','2ND FLOOR ','DELHI','KASHMIR',12653),(30,'VIKAS','DHIMAN','VIKAS@GMAIL.COM','3RD FLOOR GANDHI NAGAR','MUMBAI','KARNATAKA',11543),(40,'TARUN','KUMAR','TARUN@GMAIL.COM','4TH FLOOR GANDHI NAGAR','OOTY','HARYANA',99653),(50,'NITIN','SHARMA','NITIN@GMAIL.COM','5TH BLOCK JAYA NAGAR','SAN JOSE','UTTAR PRADESH',88643);

SELECT *FROM CUSTOMERS

CREATE VIEW CUSTOMER_SAN_JOSE AS
SELECT * FROM CUSTOMERS WHERE CITY = 'SAN JOSE'
SELECT * FROM CUSTOMER_SAN_JOSE
/*2. Inside a transaction, update the first name of the customer to Francis
where the last name is Jordan:
a. Rollback the transaction
b. Set the first name of customer to Alex, where the last name is
Jordan*/
BEGIN TRANSACTION
UPDATE CUSTOMERS SET FIRST_NAME = 'FRANCIS' WHERE LAST_NAME = 'JORDON';
SELECT* FROM CUSTOMERS
--a. Rollback the transaction
ROLLBACK TRANSACTION
SELECT * FROM CUSTOMERS
--b. Set the first name of customer to Alex, where the last name is Jordan
UPDATE CUSTOMERS SET FIRST_NAME = 'ALEX' WHERE LAST_NAME = 'JORDON';
SELECT * FROM CUSTOMERS

/*3. Inside a TRY... CATCH block, divide 100 with 0, print the default error
message. 4. Create a transaction to insert a new record to Orders table and save it*/

BEGIN TRY
SELECT 100/0 AS MESSAGE
END TRY
BEGIN CATCH
SELECT ERROR_MESSAGE() AS ERRORMESSAGE
END CATCH
--
CREATE TABLE ORDERS(ORDER_ID INT,ORDER_DATE DATE,AMOUNT INT,CUSTOMER_ID INT);SELECT * FROM ORDERS;INSERT INTO ORDERS VALUES(100,'2020-10-01',9000,20),(110,'2020-10-02',8000,30),(111,'2020-10-03',7000,3),(112,'2020-10-04',6000,2),(113,'2020-10-05',5000,5),(114,'2020-10-06',4000,10);
--TRANSACTION TO INSERT A NEW RECORD TO ORDER TABLE AND SAVE IT
BEGIN TRANSACTION
-- INSERTING NEW RECORDS
INSERT INTO ORDERS
VALUES
(110,'2023-7-22', 7500,40)
SELECT * FROM ORDERS
--ROLLBACK TRANSACTION 
--COMMIT THE TRANSACTION
COMMIT

